<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLbjqogc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLbjqogc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLbjqogc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLbjqogc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLbjqogc\appProdProjectContainer([
    'container.build_hash' => 'Lbjqogc',
    'container.build_id' => 'fe5f0e8e',
    'container.build_time' => 1578422321,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLbjqogc');
